name: Build TDLib (Linux)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Clone TDLib source
        run: |
          git clone https://github.com/tdlib/td.git
          cd td
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git zlib1g-dev libssl-dev

      - name: Build TDLib
        run: |
          cd td
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target tdjson -j$(nproc)

      - name: Package library and headers
        run: |
          cd td
          mkdir dist
          cp build/libtdjson.so dist/
          cp -r td dist/
          cd dist
          zip -r ../../tdlib-linux.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-linux
          path: tdlib-linux.zip
