name: Build TDLib for Android (Java + JNI)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TDLib source
        uses: actions/checkout@v4
        with:
          repository: tdlib/td
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build unzip openjdk-17-jdk

      - name: Download Android SDK Command-Line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk.zip
          mv cmdline-tools latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
              "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125" "cmake;3.22.1"

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/26.1.10909125" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmake/3.22.1/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/ndk/26.1.10909125" >> $GITHUB_PATH

      - name: Verify SDK + NDK paths
        run: |
          echo "SDK: $ANDROID_SDK_ROOT"
          echo "NDK: $ANDROID_NDK_HOME"
          ls $ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake

      - name: Configure TDLib build for Android
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_NATIVE_API_LEVEL=21 \
                -DCMAKE_BUILD_TYPE=Release \
                -DTD_ENABLE_JNI=ON \
                -DTD_ENABLE_DOTNET=OFF \
                -G Ninja \
                ..

      - name: Build TDLib core + JNI
        run: |
          cd build
          cmake --build . --target tdjson_static -- -j$(nproc)
          cmake --build . --target tdjni -- -j$(nproc)

      - name: Generate Java bindings
        run: |
          mkdir -p tdlib-java
          cd build
          # Generate TdApi.java and Client.java
          ./td/generate/scheme/td_generate_java_api.py td/generate/scheme/td_api.tl ../tdlib-java org/drinkless/tdlib
          cd ../tdlib-java
          find . -type f

      - name: Package output
        run: |
          mkdir -p output
          cp build/libtdjsonandroid.so output/
          cp -r tdlib-java output/java
          tar -czf tdlib-android-java.tar.gz output
          ls -lh tdlib-android-java.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-android-java
          path: tdlib-android-java.tar.gz
