name: Build TDLib for Android (all ABIs) with version info

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ git php zlib1g-dev libssl-dev default-jdk unzip

      - name: Clone TDLib
        run: |
          git clone https://github.com/tdlib/td.git tdlib
          cd tdlib
          git checkout master

      - name: Setup Android NDK
        uses: android/setup-android@v2
        with:
          ndk-version: r25c

      - name: Build TDLib for each ABI
        run: |
          ABIS=("arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          for ABI in "${ABIS[@]}"; do
            mkdir -p tdlib/build-$ABI
            cd tdlib/build-$ABI
            cmake -DCMAKE_BUILD_TYPE=Release \
                  -DTD_ENABLE_JNI=ON \
                  -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                  -DANDROID_ABI=$ABI \
                  -DANDROID_PLATFORM=android-21 \
                  ..
            cmake --build . --target tdjson -- -j$(nproc)
            cmake --build . --target tdjson_static -- -j$(nproc)
            cd ../..
          done

      - name: Save TDLib version info
        run: |
          cd tdlib
          VERSION=$(git describe --tags --always)
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          mkdir -p ../build-output
          echo "{\"tdlib_version\": \"$VERSION\", \"build_time\": \"$TIMESTAMP\"}" > ../build-output/tdlib-version.json
          cd ..

      - name: Copy Java files
        run: |
          mkdir -p build-output/java
          cp -r tdlib/example/java/* build-output/java/

      - name: Copy JNI libraries for all ABIs
        run: |
          mkdir -p build-output/lib
          ABIS=("arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          for ABI in "${ABIS[@]}"; do
            mkdir -p build-output/lib/$ABI
            cp tdlib/build-$ABI/libtdjni.so build-output/lib/$ABI/
          done

      - name: Upload build-output folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-android
          path: build-output/
